### ISSUE TITLE
Internalize `like_escape()` and `esc_sql()` functions to avoid `$wpdb` dependency

### ISSUE THREAD

**Issue by andrewalcantara** [wp-cli/db-command#65]
Received a Fatal Error when running the following command:

```
$ wp db search "hello" --path=/Users/andrew/wp/

Fatal error: Call to undefined function like_escape() in /Users/andrew/wp-cli/db-command/src/DB_Command.php on line 1081
```

Scenarios:
1. When running the command inside the db-command directory, that is when the error appear.
2. When running the command in my home directory, the error does not appear.

My environment:

```
$ wp --info
PHP binary:	/usr/bin/php
PHP version:	5.6.30
php.ini used:	
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/andrew/wp-cli/db-command
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	/Users/andrew/wp-cli/db-command/wp-cli.yml
WP-CLI version:	1.4.1
```

**Comment by miya0001** [comment]
Thanks @andrewalcantara 😊 

I saw the same problem with the behat like following.

```
  Scenario: Search with custom colors                                                                                                                                # features/db-search.feature:897
    Given a WP install                                                                                                                                               # features/steps/given.php:73
    When I run `SHELL_PIPE=0 wp db search example.com`                                                                                                               # features/steps/when.php:29
      $ SHELL_PIPE=0 wp db search example.com
      
      Fatal error: Uncaught Error: Call to undefined function like_escape() in src/DB_Command.php:1081
      Stack trace:
      #0 src/DB_Command.php(864): DB_Command::esc_like('example.com')
      #1 [internal function]: DB_Command->search(Array, Array)
      #2 vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(81): call_user_func(Array, Array, Array)
      #3 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
      #4 vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(401): call_user_func(Object(Closure), Array, Array)
      #5 vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(323): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
      #6 vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(330): WP_CLI\Runner->run_command(Array, Array)
      #7 vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php( in src/DB_Command.php on line 1081
      
      PHP Fatal error:  Uncaught Error: Call to undefined function like_escape() in src/DB_Command.php:1081
      Stack trace:
      #0 src/DB_Command.php(864): DB_Command::esc_like('example.com')
      #1 [internal function]: DB_Command->search(Array, Array)
      #2 vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(81): call_user_func(Array, Array, Array)
      #3 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
      #4 vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(401): call_user_func(Object(Closure), Array, Array)
      #5 vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(323): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
      #6 vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(330): WP_CLI\Runner->run_command(Array, Array)
      #7 vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php( in src/DB_Command.php on line 1081
      cwd: /var/folders/r8/93smf9ld3lgdsn7ly3s5hj940000gr/T/wp-cli-test-run-db-search.feature.897-5a245cf9a89898.01545215/
      run time: 0.33373379707336
      exit status: 255
```

**Comment by miya0001** [comment]
@schlessera 

It looks same problem with you said at contributor day in WCUS.

**Comment by gitlost** [comment]
Somewhat related https://github.com/wp-cli/wp-cli/pull/4527#discussion_r152706464

If you do
```
composer require wp-cli/core-command:dev-master # Make sure have latest wp-cli master
git checkout composer.json # Undo the composer.json change
```
then the problem should hopefully disappear.

(However I think it would make sense to shim these 2 WP functions `like_escape()` and `esc_sql()` both here in `db-command` and in `search-replace` as they're trivial and would avoid any dependency except on `wpdb`.)

**Comment by schlessera** [comment]
Related: https://github.com/wp-cli/db-command/issues/66
